contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/Chia-Network/chia-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/Chia-Network/chia-blockchain/discussions/new?category=ideas
  - about: Get support in the Chia Discord chat channels.
    name: Join the Discord support chat
    url: "https://discord.gg/chia"
