network_id: testnet  # testnet/mainnet

harvester:
  # The harvester server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8448
  farmer_peer:
    host: 127.0.0.1
    port: 8447
  # Location of all the plots, default ./plots
  # plot_root: "/mnt/pos"

farmer:
  # The farmer server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8447
  # The farmer will attempt to connect to this full node and harvester
  full_node_peer:
    host: 127.0.0.1
    port: 8444
  harvester_peer:
    host: 127.0.0.1
    port: 8448
  # To send a share to a pool, a block must be faster than this, in seconds
  pool_share_threshold: 7000
  # To send to the full node, a block must be faster than this, in seconds
  propagate_threshold: 5000

timelord:
  # The timelord server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8446
  # How much recursion to use for the wesolowski VDF proof. This increases the size
  # of the proofs.
  n_wesolowski: 2
  # VDF servers will be spawned at these ports, and closed after generating proofs
  # Adding more vdf servers will increase memory usage and CPU usage.
  vdf_server_ips:
    - 127.0.0.1
  vdf_server_ports:
    - 8889
  servers_ips_estimate:
    ip:
      - 127.0.0.1
    ips:
      - 100000
  full_node_peer:
      host: 127.0.0.1
      port: 8444

full_node:
  # The full node server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8444
  enable_upnp: True
  # Don't send any more than these number of headers and blocks, in one message
  max_headers_to_send: 25
  max_blocks_to_send: 5
  num_sync_batches: 10

  # If node is more than these blocks behind, will do a sync
  sync_blocks_behind_threshold: 20

  # This SSH key is for the ui SSH server
  ssh_filename: config/ssh_host_key
  # How often to connect to introducer if we need to learn more peers
  introducer_connect_interval: 120
  # Continue trying to connect to more peers until this number of connections
  target_peer_count: 10

  farmer_peer:
      host: 127.0.0.1
      port: 8447
  timelord_peer:
      host: 127.0.0.1
      port: 8446
  introducer_peer:
      # host: 2600:1f18:63ed:e200:f7c5:9e28:9b5e:130  # Chia AWS introducer IPv6
      # host: 127.0.0.1
      host: 18.232.223.201  # Chia AWS introducer IPv4
      port: 8444

introducer:
  host: 127.0.0.1
  port: 8445
  max_peers_to_send: 20
