instance-1:
  log_filename: "s3_plugin.log"
  log_level: INFO
  server_files_location: "/Users/test/.chia/mainnet/data_layer/db/server_files_location_testnet10"
  port: 8998
  aws_credentials:
    access_key_id: "xxx"
    secret_access_key: "xxx"
    region: "xxx"

  stores:
    - store_id: "7acfcbd1ed73bfe2b698508f4ea5ed353c60ace154360272ce91f9ab0c8423c3"
      upload_bucket: "chia-datalayer-test-bucket-2"
      download_urls: ["s3://hello", "s3://goodbye"]
    - store_id: "a14daf55d41ced6419bcd011fbc1f74ab9567fe55340d88435aa6493d628fa47"
      upload_bucket:
      download_urls: ["s3://hello", "s3://goodbye"]

instance-2:
  port: 8999
  server_files_location: "/Users/test/.chia/mainnet/data_layer/db/server_files_location_testnet10"
  aws_credentials:
    access_key_id: "xxx"
    secret_access_key: "xxx"
    region: "xxx"

  stores:
    - store_id: "7acfcbd1ed73bfe2b698508f4ea5ed353c60ace154360272ce91f9ab0c8423c3"
      upload_bucket: ""
      download_urls: []
    - store_id: "a14daf55d41ced6419bcd011fbc1f74ab9567fe55340d88435aa6493d628fa47"
      upload_bucket: "chia-datalayer-test-bucket-1"
      download_urls: []
