
instance-1:
  port: 8998
  aws_credentials:
    access_key_id: "xxx"
    secret_access_key: "xxx"
    region: "xxx"

  store_ids: ["xxx"]

  urls: [ "xxx"]

  buckets:
    chia-datalayer-test-bucket-2: ["xxx"]

instance-2:
  port: 8999
  aws_credentials:
    access_key_id: "xxx"
    secret_access_key: "xxx"
    region: "xxx"

  store_ids: ["xxx", "xxx" ]

  urls: [ "xxx"]

  buckets:
    chia-datalayer-test-bucket-1: [ "xxx", "xxx" ]
