name: ğŸ•µï¸â€â™€ï¸ fmt-diagnostics

on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: fmt-diagnostics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt-diagnostics:
    name: ğŸ•µï¸â€â™€ï¸ fmt-diagnostics ${{ matrix.location.name }} ${{ matrix.platform.emoji }} - ${{ matrix.platform.name }} ${{ matrix.arch.name }}
    runs-on: ${{ matrix.platform.runs-on }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux GitHub
            os: linux
            emoji: ğŸ§
            runs-on: ubuntu-latest
          - name: Linux FMT
            os: linux
            emoji: ğŸ§
            runs-on: linux-arm64-fmt
          - name: Linux MSP
            os: linux
            emoji: ğŸ§
            runs-on: linux-arm64-msp
          - name: macOS GitHub
            os: macos
            emoji: ğŸ
            runs-on: macos-12
          - name: macOS FMT
            os: macos
            emoji: ğŸ
            runs-on: macos-arm64-fmt
          - name: macOS MSP
            os: macos
            emoji: ğŸ
            runs-on: macos-arm64-msp
          - name: Windows
            os: windows
            emoji: ğŸªŸ
            runs-on: windows-latest

    steps:
      - uses: chia-network/actions/clean-workspace@main

      - uses: chia-network/actions/git-mark-workspace-safe@main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - shell: python
        run: |
          import pathlib

          diag_directory = pathlib.Path.home().joinpath("actions-runner", "_diag")
          log_paths = {}
          for prefix in ["Runner_", "Worker_"]:
              latest = max(
                  diag_directory.glob(f"{prefix}*"),
                  key=lambda x: x.stat().st_mtime,
              )
              log_paths[prefix] = latest

          for prefix, path in log_paths.items():
              print(f"{prefix!r} log: {path}")
