name: ğŸ•µï¸â€â™€ï¸ fmt-diagnostics

on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: fmt-diagnostics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt-diagnostics:
    name: ğŸ•µï¸â€â™€ï¸ ${{ matrix.platform.emoji }} ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux GitHub
            os: linux
            emoji: ğŸ§
            runs-on: ubuntu-latest
          - name: Linux FMT
            os: linux
            emoji: ğŸ§
            runs-on: linux-arm64-fmt
          - name: Linux MSP
            os: linux
            emoji: ğŸ§
            runs-on: linux-arm64-msp
          - name: macOS GitHub
            os: macos
            emoji: ğŸ
            runs-on: macos-12
          - name: macOS FMT
            os: macos
            emoji: ğŸ
            runs-on: mac-arm64-fmt
          - name: macOS MSP
            os: macos
            emoji: ğŸ
            runs-on: mac-arm64-msp
          - name: Windows
            os: windows
            emoji: ğŸªŸ
            runs-on: windows-latest

    steps:
      - uses: chia-network/actions/clean-workspace@main

      - uses: chia-network/actions/git-mark-workspace-safe@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          diag=~/actions-runner/_diag
          if [ -d "${diag}" ]
          then
            for prefix in Runner_ Worker_
            do
              log=$(ls -t ${diag}/${prefix}*.log | head -n 1)
              echo ${log}
              cp ${log} artifacts
            done
          else
            echo "No diagnostics directory found at ${diag}"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: artifacts/
          if-no-files-found: error
