name: Build Windows Installer

on: [push, pull_request]

jobs:
  build:
    name: Build Windows .msi
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: '3.7'

    - name: Build source distribution of chia-blockchain
      run: |
        pip install pep517
        python -m pep517.build --source --out-dir ${{ github.workspace }}\electron-wix\build .
        echo "::set-env name=scm_version::$GITHUB_REF"
        python -c "import sys; print(sys.version)"

    - name: View version info
      run: |
        dir ${{ github.workspace }}\electron-wix\build
        python -m setup.py --version
        python -c "import sys; print(sys.version)"

    - name: Install python requirements
      run: |
        $pythonLocation\python3 -m venv venv
        . .\venv\Scripts\Activate.ps1
        pip install --upgrade pip
        pip install -i https://download.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10 cbor2==5.1.0
      #pip install .


    - name: Install electron-packager
      run: |
        npm install electron-packager -g

    #- name: Install .NET 3.5.1
      #uses: actions/setup-dotnet@v1 # https://github.com/actions/setup-dotnet
      #with:
        #dotnet-version: '3.5.100' # SDK Version to use.
    #- run: dotnet build <my project>

    - name: npm install
      working-directory: ${{ github.workspace }}\electron-ui
      run: |
        npm install --runtime=electron --target=1.7.6

    - name: curl Visual C++ 2019 redistributable
      working-directory: ${{ github.workspace }}\electron-wix\prerequisites\
      run: curl --remote-name --show-error --fail https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: curl Python 3.7.7 redistributable
      working-directory: ${{ github.workspace }}\electron-wix\prerequisites\
      run: curl --remote-name --show-error --fail https://www.python.org/ftp/python/3.7.7/python-3.7.7-embed-amd64.zip

    #- name: Build Windows installer
      #env:
        #version: 0.1.5 # Need to get this from setuptools_scm
      #working-directory: ${{ github.workspace }}\electron-wix
      #run: |
        #.\rebuild-all.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ github.workspace }}\electron-wix\build
