name: Build Windows Installer

on: [push, pull_request]

jobs:
  upload_source_dist:
    name: Upload source distribution
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - name: Install electron-packager
      run: |
        npm install electron-packager -g

    #- name: Install .NET 3.5.1
      #run: |
      # npm install electron-packager -g

    - name: See working directory
        working-directory: ${{ github.workspace }}
        run: ls -la

    - name: npm install
      working-directory: ${{ github.workspace }}/electron-ui
      run: |
        npm install --runtime=electron --target=1.7.6

    - name: wget Visual C++ 2019 redistributable
      uses: wei/wget@v1
      with:
        args: -P ${{ github.workspace }}/electron-wix/prerequisites/ https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: Build Windows installer
      env:
        version: 0.1.5 # Need to get this from setuptools_scm
      working-directory: ${{ github.workspace }}/electron-wix
      run: |
        .\rebuild-all.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ github.workspace }}/electron-wix/build
