name: Build Windows Installer

on: [push, pull_request]

jobs:
  build:
    name: Build Windows .msi
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - name: Install electron-packager
      run: |
        npm install electron-packager -g

    #- name: Install .NET 3.5.1
      #uses: actions/setup-dotnet@v1 # https://github.com/actions/setup-dotnet
      #with:
        #dotnet-version: '3.5.100' # SDK Version to use.
    #- run: dotnet build <my project>

    - name: See working directory
      #working-directory: ${{ github.workspace }}
      working-directory: $GITHUB_WORKSPACE
      run: dir .

    - name: npm install
      working-directory: $GITHUB_WORKSPACE\electron-ui
      run: |
        npm install --runtime=electron --target=1.7.6

    - name: wget Visual C++ 2019 redistributable
      uses: wei/wget@v1
      with:
        args: -P $GITHUB_WORKSPACE\electron-wix\prerequisites\ https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: Build Windows installer
      env:
        version: 0.1.5 # Need to get this from setuptools_scm
      working-directory: $GITHUB_WORKSPACE\electron-wix
      run: |
        .\rebuild-all.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: $GITHUB_WORKSPACE\electron-wix/build
