name: Build Windows Installer

on: [push, pull_request]

jobs:
  build:
    name: Build Windows Installer
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          # we need fetch-depth 0 so setuptools_scm can resolve tags

      - uses: actions/setup-python@v1
        name: Install Python 3.7
        with:
          python-version: "3.7"
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Build Windows installer with build_scripts\build_windows.ps1
        working-directory: ${{ github.workspace }}\build_scripts
        run: |
          git config --global core.longpaths true
          ./build_windows.ps1

      - name: Upload Windows exe's to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Exe
          path: ${{ github.workspace }}\electron-react\Chia-0.1.6-win32-x64

      - name: Upload Installer to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Installers
          path: ${{ github.workspace }}\electron-react\release-builds\
