name: Build Windows Installer

on: [push, pull_request]

jobs:
  build:
    name: Build Windows .msi
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: '3.7'

    - name: curl miniupnpc and setproctitle
      working-directory: ${{ github.workspace }}\electron-wix\blockchain
      run: |
        curl -OL --show-error --fail https://download.chia.net/simple/miniupnpc/miniupnpc-2.1-cp37-cp37m-win_amd64.whl
        curl -OL --show-error --fail https://download.chia.net/simple/setproctitle/setproctitle-1.1.10-cp37-cp37m-win_amd64.whl

    - name: Create and collect all wheels for chia-blockchain
      run: |
        pip install pep517 wheel
        pip wheel --use-pep517 --only-binary cbor2 --extra-index-url https://download.chia.net/simple/ -f ${{ github.workspace }} --wheel-dir=${{ github.workspace }}\electron-wix\blockchain ${{ github.workspace }}\.

    - name: Install electron-packager
      run: |
        npm install electron-packager -g

    - name: npm install
      working-directory: ${{ github.workspace }}\electron-ui
      run: |
        npm install --runtime=electron --target=1.7.6

    - name: curl Visual C++ 2019 redistributable # Windows has curl natively
      working-directory: ${{ github.workspace }}\electron-wix\prerequisites\
      run: curl -OL --show-error --fail https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: curl Python 3.7.6 Installer
      working-directory: ${{ github.workspace }}\electron-wix\prerequisites\
      run: curl -OL --show-error --fail https://www.python.org/ftp/python/3.7.6/python-3.7.6-amd64.exe

    - name: Build Windows installer with Wix
      env:
        version: 0.1.8 # TODO Need to create this from setuptools_scm for Windows
      working-directory: ${{ github.workspace }}\electron-wix
      run: |
        .\rebuild-all.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Windows-Installers
        path: ${{ github.workspace }}\electron-wix\final
